### ISSUE TITLE
lef_join, right_join, run methodu basicdb sınıfı içinde bulunamadı

### ISSUE THREAD

**Issue by cetinkocak** [tayfunerbilen/basicdb#31]
Merhabalar, kolaylık olması açısından sizin basicdb sınıfını kullanıyorum ancak all.php içerisinde vermiş olduğunuz örnekler de olduğu gibi left_join right_join aralarında alt tre olmadan kullanılıyor ayrıca bu fonksiyonları run(); ile çalıştıramadım ve maalesef bu işte o kadar iyi olmadığımdan hangi kod ile çalıştırabilirim anlamadım. run(); kullandığımda run komutu basicdb sınıfı içerisinde bulunamadı hataı almaktayım. Bu fonksiyonları nasıl kullanabilirim teşekkürler.

**Comment by cetinkocak** [comment]
BasicDB tekrar kontrol ettiğimde run() yeerine all() kullanmam gerektiğini anladım. Tecrübe oldu ve burada düzeltilmesigereken bir şeyler de bulmuş olduk. Hata değil değişiklik olduğunu fark ettik. Herkese kolay gelsin.

**Comment by tayfunerbilen** [comment]
evet ~`left_join()`~ yerine `leftJoin()`, ~`right_join()`~ yerine `rightJoin()`, ~`run()`~ yerine `all()`, ~`run(true)`~ yerine `first()` metodlarını kullanıyoruz artık.
