### ISSUE TITLE
Fatal error line 111

### ISSUE THREAD

**Issue by koyuyesil** [tayfunerbilen/basicdb#4]
php error logdan baktımda bağlantı hatası veriyor. PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Hedef makine etkin olarak reddetti. ama sorun olmaması gerekiyor. bende anlamadım. hostta çalışıyor

**Comment by ismailcaakir** [comment]
Uzak bağlantılara izin vermeniz gerekiyor. Bunu cpanel kullanıyorsanız mysql remote server üzerinden ip'nize izin ekleyerek veya joker ekleyerek " % " çözebilirsiniz.

**Comment by ilkerkya** [comment]
Myslq'de "SELECT * FROM player.player" diye kullandığımız komutu burada nasıl kullanacağız? Ek olarak bağlantı sırasında veritabanı adı zorunlu kılınmış. Bunu nasıl engelleyip bu tarz bir sorgu kullanacağız? Kısacası tek veritabanı yerine birden çok veritabanına nasıl bağlanacağız?
